import type { Plan } from '@/types/plan'

export const DEMO_PLAN: Plan = {
  id: 'example-spb',
  fromCity: 'Москва',
  toCity: 'Санкт-Петербург',
  dates: '10–15 мая',
  days: 5,
  pax: 1,
  budget: 20000,
  interests: 'all',
  createdAt: '2026-04-25T10:00:00Z',
  bookingStatus: 'not_booked',

  flights: {
    there: [
      {
        id: 'tt-sapsan-767',
        type: 'train',
        badge: 'best',
        carrier: 'Сапсан 767А',
        number: '767А',
        departTime: '06:50',
        arriveTime: '10:55',
        departCity: 'Москва, Ленинградский',
        arriveCity: 'СПб, Московский',
        duration: '4 ч 05 мин',
        price: 2890,
        url: 'https://www.tutu.ru/poezda/?from_id=2000000&to_id=2004000',
      },
      {
        id: 'tt-sapsan-757',
        type: 'train',
        badge: 'fastest',
        carrier: 'Сапсан 757А',
        number: '757А',
        departTime: '13:00',
        arriveTime: '16:50',
        departCity: 'Москва, Ленинградский',
        arriveCity: 'СПб, Московский',
        duration: '3 ч 50 мин',
        price: 4190,
        url: 'https://www.tutu.ru/poezda/?from_id=2000000&to_id=2004000',
      },
      {
        id: 'tt-night',
        type: 'train',
        badge: 'cheapest',
        carrier: 'Гранд Экспресс №053',
        number: '053',
        departTime: '23:55',
        arriveTime: '08:36',
        departCity: 'Москва, Ленинградский',
        arriveCity: 'СПб, Московский',
        duration: '8 ч 41 мин',
        price: 2150,
        url: 'https://www.tutu.ru/poezda/?from_id=2000000&to_id=2004000',
      },
    ],
    back: [
      {
        id: 'tt-back-sapsan',
        type: 'train',
        badge: 'best',
        carrier: 'Сапсан 758А',
        number: '758А',
        departTime: '17:00',
        arriveTime: '20:50',
        departCity: 'СПб, Московский',
        arriveCity: 'Москва, Ленинградский',
        duration: '3 ч 50 мин',
        price: 2890,
        url: 'https://www.tutu.ru/poezda/?from_id=2004000&to_id=2000000',
      },
      {
        id: 'tt-back-fastest',
        type: 'train',
        badge: 'fastest',
        carrier: 'Сапсан 754А',
        number: '754А',
        departTime: '09:00',
        arriveTime: '12:45',
        departCity: 'СПб, Московский',
        arriveCity: 'Москва, Ленинградский',
        duration: '3 ч 45 мин',
        price: 4350,
        url: 'https://www.tutu.ru/poezda/?from_id=2004000&to_id=2000000',
      },
      {
        id: 'tt-back-cheap',
        type: 'train',
        badge: 'cheapest',
        carrier: 'Поезд №025А',
        number: '025А',
        departTime: '22:30',
        arriveTime: '06:55',
        departCity: 'СПб, Московский',
        arriveCity: 'Москва, Ленинградский',
        duration: '8 ч 25 мин',
        price: 1980,
        url: 'https://www.tutu.ru/poezda/?from_id=2004000&to_id=2000000',
      },
    ],
  },

  hotels: [
    {
      id: 'hl-kazan',
      name: 'Апартаменты Казанский',
      stars: 0,
      rating: 8.7,
      reviews: 412,
      tags: ['Центр', 'Wi-Fi', 'Бесп. отмена'],
      pricePerNight: 3200,
      totalPrice: 12800,
      url: 'https://search.hotellook.com/?destination=Saint+Petersburg',
      address: 'Казанская ул., 7, Санкт-Петербург',
      lat: 59.932,
      lng: 30.323,
    },
    {
      id: 'hl-nevsky',
      name: 'Отель Невский Форум 4★',
      stars: 4,
      rating: 8.9,
      reviews: 1183,
      tags: ['Центр', 'Завтрак', 'Бесп. отмена'],
      pricePerNight: 5400,
      totalPrice: 21600,
      url: 'https://search.hotellook.com/?destination=Saint+Petersburg',
      address: 'Невский пр., 69, Санкт-Петербург',
      lat: 59.932,
      lng: 30.349,
    },
    {
      id: 'hl-petr',
      name: 'Бутик-отель Петровский',
      stars: 4,
      rating: 9.1,
      reviews: 246,
      tags: ['Центр', 'Завтрак', 'Wi-Fi'],
      pricePerNight: 6800,
      totalPrice: 27200,
      url: 'https://search.hotellook.com/?destination=Saint+Petersburg',
      address: 'наб. реки Мойки, 22, Санкт-Петербург',
      lat: 59.939,
      lng: 30.318,
    },
  ],

  itinerary: [
    {
      day: 1,
      title: 'Прогулка по центру',
      date: '10 мая, пт',
      pois: [
        {
          time: '11:00',
          name: 'Дворцовая площадь и Эрмитаж',
          type: 'museum',
          duration: '3 ч',
          cost: '500 ₽',
          address: 'Дворцовая пл., 2',
          description: 'Главная площадь и крупнейший музей мира.',
          lat: 59.939,
          lng: 30.314,
        },
        {
          time: '14:30',
          name: 'Обед в Pyshechnaya',
          type: 'restaurant',
          duration: '1 ч',
          cost: '350 ₽',
          address: 'Большая Конюшенная, 25',
          description: 'Легендарные ленинградские пышки с кофе с молоком.',
          lat: 59.936,
          lng: 30.323,
        },
        {
          time: '16:00',
          name: 'Невский проспект до Казанского собора',
          type: 'walk',
          duration: '1.5 ч',
          cost: '0 ₽',
          address: 'Невский пр.',
          description: 'Прогулка по главной артерии города.',
          lat: 59.934,
          lng: 30.324,
        },
      ],
    },
    {
      day: 2,
      title: 'Петропавловка и стрелка В.О.',
      date: '11 мая, сб',
      pois: [
        {
          time: '10:00',
          name: 'Петропавловская крепость',
          type: 'museum',
          duration: '2.5 ч',
          cost: '750 ₽',
          address: 'Петропавловская крепость, 3',
          description: 'Колыбель Петербурга и собор-усыпальница Романовых.',
          lat: 59.95,
          lng: 30.317,
        },
        {
          time: '13:00',
          name: 'Стрелка Васильевского острова',
          type: 'walk',
          duration: '1 ч',
          cost: '0 ₽',
          address: 'Биржевая площадь',
          description: 'Открыточный вид на Неву и Зимний дворец.',
          lat: 59.944,
          lng: 30.306,
        },
        {
          time: '15:00',
          name: 'Кофе и пирожки в Пироговый дворик',
          type: 'restaurant',
          duration: '40 мин',
          cost: '380 ₽',
          address: 'Большая Морская, 6',
          description: 'Уютная пирожковая в центре.',
          lat: 59.934,
          lng: 30.32,
        },
      ],
    },
    {
      day: 3,
      title: 'Пушкин и Царское село',
      date: '12 мая, вс',
      pois: [
        {
          time: '10:00',
          name: 'Екатерининский дворец',
          type: 'museum',
          duration: '3 ч',
          cost: '900 ₽',
          address: 'Садовая ул., 7, Пушкин',
          description: 'Янтарная комната и парадные залы.',
          lat: 59.716,
          lng: 30.396,
        },
        {
          time: '14:30',
          name: 'Обед в Старая башня',
          type: 'restaurant',
          duration: '1 ч',
          cost: '950 ₽',
          address: 'Академический пр., 14, Пушкин',
          description: 'Локальная кухня в исторической усадьбе.',
          lat: 59.718,
          lng: 30.398,
        },
        {
          time: '16:00',
          name: 'Прогулка по Екатерининскому парку',
          type: 'walk',
          duration: '2 ч',
          cost: '200 ₽',
          address: 'Екатерининский парк',
          description: 'Гроты, пруды и Камеронова галерея.',
          lat: 59.715,
          lng: 30.402,
        },
      ],
    },
    {
      day: 4,
      title: 'Музеи Серебряного века',
      date: '13 мая, пн',
      pois: [
        {
          time: '11:00',
          name: 'Русский музей',
          type: 'museum',
          duration: '2.5 ч',
          cost: '500 ₽',
          address: 'Инженерная ул., 4',
          description: 'Главное собрание русского искусства.',
          lat: 59.938,
          lng: 30.331,
        },
        {
          time: '14:30',
          name: 'Кафе Север-Метрополь',
          type: 'restaurant',
          duration: '1 ч',
          cost: '700 ₽',
          address: 'Невский пр., 44',
          description: 'Старейшее кафе города с тортами с 1903 года.',
          lat: 59.935,
          lng: 30.331,
        },
        {
          time: '16:30',
          name: 'Спас-на-Крови',
          type: 'museum',
          duration: '1.5 ч',
          cost: '450 ₽',
          address: 'наб. канала Грибоедова, 2А',
          description: 'Мозаичный собор-памятник.',
          lat: 59.94,
          lng: 30.329,
        },
      ],
    },
    {
      day: 5,
      title: 'Острова и закат',
      date: '14 мая, вт',
      pois: [
        {
          time: '11:00',
          name: 'Прогулка по Каменному острову',
          type: 'walk',
          duration: '2 ч',
          cost: '0 ₽',
          address: 'Каменный остров',
          description: 'Старинные дачи в зелени.',
          lat: 59.987,
          lng: 30.307,
        },
        {
          time: '14:00',
          name: 'Обед в Beer Brothers',
          type: 'restaurant',
          duration: '1 ч',
          cost: '850 ₽',
          address: 'Большая Конюшенная, 14',
          description: 'Бургеры и крафт перед поездом.',
          lat: 59.938,
          lng: 30.323,
        },
        {
          time: '16:00',
          name: 'Закат на крыше Лофт-проекта Этажи',
          type: 'walk',
          duration: '1 ч',
          cost: '350 ₽',
          address: 'Лиговский пр., 74',
          description: 'Панорамный вид на крыши Питера.',
          lat: 59.926,
          lng: 30.355,
        },
      ],
    },
  ],

  optimal: {
    transport_there: {
      name: 'Сапсан 767А · 06:50 → 10:55',
      why: 'Центр→центр, без пересадок, быстрее самолёта по двери-в-дверь',
      price: '2 890 ₽',
    },
    hotel: {
      name: 'Апартаменты Казанский',
      why: '8.7★ · 5 минут до Невского · бесплатная отмена',
      price_per_night: '3 200 ₽/ночь',
    },
    transport_back: {
      name: 'Сапсан 758А · 17:00 → 20:50',
      why: 'Удобный вечерний рейс, в Москве к 9 вечера',
      price: '2 890 ₽',
    },
  },
}
